### ISSUE TITLE
Are there any good first issues? (also, HacktoberFest2022)

### ISSUE THREAD

**Issue by mrandri19** [mindsdb/type_infer#12]
Hi! Last year I had a great experience contributing to MindsDB's repos during the HacktoberFest.
This year I am not competing for MindsDB's own competition as I have less free time, but I was still looking for some cool and small issues I could help you with (and get that 2022 shirt :) ).

I was wondering if `type_infer` had any good first issues that could be labelled with the hacktoberfest label.

I have been writing a small typechecker for pandas + numpy + sklearn on my own, mainly to avoid losing my mind while refactoring some pipelines for Kaggle competitions, so this project looks right up my alley.

**Comment by paxcema** [comment]
Hey @mrandri19! Glad to see you back around for more action 😄, your contributions last year were amazing 🚀 

Yes, absolutely. This package is actually brand new but it is valid for Hacktoberfest all the same. It is part of a series of small refactor efforts where logic is moved out of `mindsdb/lightwood` to enable other ML frameworks that may want to use some parts of its pipeline. In particular:

1. Type inference (this repo)
2. Data analysis
3. Model evaluation
4. Model-agnostic analysis and explainability techniques 

As of just a few minutes ago, this repo is considered functional and ready to use by lightwood's branch `use_typeinfer`.  However, this is just the start, as we'd like this to evolve into a package that is useful for any tabular ML project, regardless of the framework of choice. 

In terms of good first issues, I will be tagging some of the currently existing ones, but most of all I believe documentation needs polishing. I will open up some specific issues this week, but feel free to explore and generally improve things, and the PR will certainly receive a `hacktoberfest-valid` tag!

**Comment by mrandri19** [comment]
Oh wow, that's amazing, thanks @paxcema!

I will explore a bit and see what can be polished and cleaned up.

**Comment by ZoranPandovski** [comment]
Welcome back @mrandri19 :wave: Also, feel free to browse through our current 110 open issues for Hacktoberfest https://github.com/mindsdb/mindsdb/projects/12
