### ISSUE TITLE
Add documentation link to README.md

### ISSUE THREAD

**Issue by paxcema** [mindsdb/type_infer#13]
We are currently hosting docs at https://mindsdb.github.io/type_infer, but this is not being communicated.

**Comment by hamzabohra** [comment]
can i work on this?

**Comment by sarabgi** [comment]
@paxcema Could you assign me to do this task?

**Comment by paxcema** [comment]
Hey guys, first come first served. Sorry @cheigba, however feel free to work on #11, because we have a lot of things that could be improved in docs, generally. I will be posting more issues soon, so be on the lookout! 👀

**Comment by vanshv** [comment]
Are you still working on this issue @hamzabohra ? If not, I could submit a PR.

**Comment by hamzabohra** [comment]
Sorry i m not it.
Go ahead.

**Comment by hamzabohra** [comment]
Not on it*
