### ISSUE TITLE
When pct_invalid=0, no rows should be dropped

### ISSUE THREAD

**Issue by paxcema** [mindsdb/type_infer#3]

**Comment by mrandri19** [comment]
Is this bug caused by these two `dropna`s (https://github.com/mindsdb/type_infer/blob/staging/type_infer/infer.py#L383-L390)?
Because I could not find any other traces of data being skipped related to `pct_invalid`

**Comment by paxcema** [comment]
Most likely, yes. I'm not 100% familiar with this feature though (was implemented by another engineer). I do think a test should be part of the fix so that we know it's working as intended in the future.

**Comment by paxcema** [comment]
Closing, no longer accurate to say `pct_invalid` has a say in what rows are dropped prior to the type inference step.
