### ISSUE TITLE
Issue handling extremely small values or NaN

### ISSUE THREAD

**Issue by dusvyat** [mindsdb/type_infer#39]
Getting the following error when loading in context data for Writer Handler demo. My hypothesis is that is happening due to some columns containing many nulls which pandas handles as NaN.

python3.9/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

**Comment by paxcema** [comment]
Closed via #45.
